[tool.ruff]
exclude = [
    "tetragon/proto/*" # proto-generated files
]
lint.select = [
    "E",    # Enforce pycodestyle errors (style, whitespace)
    "F",    # Enforce pyflakes checks (unused imports, undefined names)
    "B",    # Enforce bugbear checks (code smells)
    "D",    # Enforce pydocstyle checks (docstrings)
    "N",    # Enforce pep8-naming checks (naming conventions)
    "C90",  # Enforce mccabe checks (complexity/nesting)
    "ANN",  # Enforce type annotation checks
    "Q",    # Enforce flake8-quotes checks (quote consistency)
    "PIE",  # Enforce flake8-pie checks (misc best practices)
    "RET",  # Enforce flake8-return checks (return statement best practices)
    "SIM",  # Enforce flake8-simplify checks (code simplification)
    "TID",  # Enforce flake8-tidy-imports checks (import conventions)
]
lint.ignore = [
    "D105",  # Ignore missing docstring in magic method (pydocstyle)
    "D203",  # Ignore requirement for 1 blank line before class docstring (pydocstyle)
    "D204",  # Ignore requirement for 1 blank line after class docstring (pydocstyle)
    "D205",  # Ignore requirement for 1 blank line between summary line and description (pydocstyle)
    "D212",  # Ignore requirement that multi-line docstring summary should start at the first line (pydocstyle)
    "D401",  # Ignore requirement that first line should be in imperative mood (pydocstyle)
    "D411",  # Ignore missing blank line before section (pydocstyle)
    "D413",  # Ignore missing blank line after last section (pydocstyle)
]
line-length=120

[project]
name = "argos-hids"
version = "0.1.0"
description = "ARGOS Host-based Intrusion Detection System (HIDS)"
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
     "h5py==3.14.0",
    "numpy==2.2.5",
    "pandas==2.2.3",
    "openpyxl==3.1.5",
    "pytorch-lightning==2.5.2",
    "torch==2.7.0",
    "torchmetrics==1.7.3",
    "requests==2.32.3",
    "grpcio>=1.74.0,<2.0.0",
    "grpcio-tools>=1.74.0,<2.0.0",
    "pyseccomp>=0.1.2,<0.2.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "async-timeout==5.0.1",
    "attrs==25.3.0",
    "certifi==2025.10.5",
    "charset-normalizer==3.4.3",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "filelock==3.19.1",
    "fonttools==4.60.1",
    "frozenlist==1.7.0",
    "fsspec==2025.9.0",
    "idna==3.10",
    "Jinja2==3.1.6",
    "kiwisolver==1.4.9",
    "MarkupSafe==3.0.3",
    "matplotlib==3.10.6",
    "mpmath==1.3.0",
    "multidict==6.6.4",
    "networkx==3.4.2",
    "packaging==25.0",
    "pillow==11.3.0",
    "propcache==0.4.0",
    "psutil==7.1.0",
    "pyparsing==3.2.5",
    "python-dateutil==2.9.0.post0",
    "scipy==1.15.3",
    "six==1.17.0",
    "sympy==1.14.0",
    "torch-geometric==2.6.1",
    "tqdm==4.67.1",
    "triton==3.4.0",
    "typing_extensions==4.15.0",
    "urllib3==2.5.0",
    "yarl==1.20.1"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
